### ISSUE TITLE
Clarify what is meant by "sync"

### ISSUE THREAD

**Issue by dmwyatt** [jahwag/ClaudeSync#18]
Some tools do two-way syncs with conflict resolution.  Some tools sync local to remote. Others sync remote to local. Others do both without conflict resolution.

From the README it's not apparent what this tool does.

**Comment by mnieber** [comment]
First of all, this tool looks amazing, I'm looking forward to trying it!

I checked the source code to see if this tool would only upload a file if it is different from the remote one. The reason is that I don't want to spam Claude.ai with repeatedly uploading the same files. 

The tool handles this correctly, which is great. But my suggestion is to explain this directly in the README (e.g. "ClaudeSync only uploads local files that are absent or different from the files in the remote project").

**Comment by jahwag** [comment]
> First of all, this tool looks amazing, I'm looking forward to trying it!
> 
> I checked the source code to see if this tool would only upload a file if it is different from the remote one. The reason is that I don't want to spam Claude.ai with repeatedly uploading the same files.
> 
> The tool handles this correctly, which is great. But my suggestion is to explain this directly in the README (e.g. "ClaudeSync only uploads local files that are absent or different from the files in the remote project").

Wouldn't it have been quicker to submit a PR for your suggested change rather than commenting on a closed issue from two weeks ago?

**Comment by mnieber** [comment]
No, not quicker (and I wanted to ask if you agree this change would help). But I will create a PR then.

Also, I just synced my first project, and I'm psyched. This is amazing, thank you.
