### ISSUE TITLE
File changed watch mode to sync

### ISSUE THREAD

**Issue by ChrisTorng** [jahwag/ClaudeSync#41]
# Feature Request Template

## 1. Problem Description
I don't like the idea of `claudesync schedule`. It will run all the time, even when I'm not in developing. And what interval is fast enough, but not too frequent to disturb claude.ai and attract the ban on my account?

## 2. Desired Solution
I wish it can run on watch mode, detect any file changed, then (wait a while) sync automatically. Or it just detects the changed files and list them. Wait for user input to continue a batch sync. Watch mode only update those changed files, not sync all files blindly. It can support accepting user input to trigger full sync.

## 3. Considered Alternatives
N/A

## 4. Use Case
I'll keep the watch mode running background, never mind to manual sync. And I don't want to use `claudesync schedule`.

## 5. Additional Context
N/A

## 6. Environment (if relevant)
N/A

## 7. Willingness to Contribute
Maybe I can try, but not confident on this job.

**Comment by jahwag** [comment]
Thank you for your suggestion!

We won't be implementing this feature because ClaudeSync is designed as a CLI tool, not a daemon. It is intended to be run manually, not as a background process.

However, nothing stops you from modifying the suggested cron/claudesync schedule to include a ps and grep for your IDE process. This way, you can achieve a similar effect based on your specific setup.

Additionally, if you're using Git, you can add a ClaudeSync project sync as a post-commit hook. This will trigger the sync automatically after each commit, potentially meeting your needs without changing the core design of ClaudeSync.
